plugins:
  - "@semantic-release/commit-analyzer"
  - '@semantic-release/release-notes-generator'
  - - '@semantic-release/exec'
    - verifyReleaseCmd: 'echo ${nextRelease.version} > VERSION.txt'
      prepareCmd: 'echo ${nextRelease.version} > VERSION.txt'
  - - '@semantic-release/changelog'
    - changelogFile: CHANGELOG.md
  - "@semantic-release/gitlab"
branches:
  - "master"
  - name: "develop"
    prerelease: "alpha"
